### ISSUE TITLE
Timecode regex crash

### ISSUE THREAD

**Issue by willosof** [bitfocus/companion-module-bmd-hyperdeck#57]
From email support:
> Not working:
> Dynamic variables Timecode
> (Id like timecode countdown)
> 
> System:
> mac air 2020 big sur 11.0.1 (20B29)
> Companion 2.1.3
> Hyperdeck studio mini (cant find firmware confirmation, but as of I dont get update prompt when connected to hyperdeck setup it should be latest update)
> 
> 1.1 When connecting to hyperdeck with companion i get syntax error popup ..have also tried with another mac pro running catalina ..same thing. When closing this (fast) I can go on about using companion ..otherwise it gets stuck and popup window keeps apearing after closing it. See attached screenshot. 
> 

<img width="1440" alt="Skärmavbild 2021-11-01 kl  11 20 13" src="https://user-images.githubusercontent.com/426386/139771463-4dada288-627f-4bcf-9947-cb98be5ac048.png">

Something is going on with this regexp. I don't see any immediate problems, but I'm looking at regex from a Perl perspective.
```
let tc = instance.transportInfo['displayTimecode'].match(
	/^(?<HMS>(?<H>\d{2}):(?<M>\d{2}):(?<S>\d{2}))[:;](?<F>\d{2})$/
)
```
variables.js line 143.

**Comment by willosof** [comment]
Blame for the line is @sphlabs :)

**Comment by krocheck** [comment]
This is a bug based on backporting for 2.1 ... our bad.  Its actually an upstream bug that was fixed, at least based on a chunk of work I did chasing this and asking @Julusian many months ago.

**Comment by sphlabs** [comment]
@krocheck so is there a fix for this in 2.1…? I don't get the error in 2.2 so that would make sense if it is a back-porting issue.

**Comment by krocheck** [comment]
Its a bug in node8 ... no, there was never a fix for 2.1 to my knowledge and the code simply works as-is in node14.

**Comment by sphlabs** [comment]
What's the policy on things like that? Is 2.1 still receiving bug fix updates, or is 2.2 close enough to release that all the focus is there now?

(not that I'm sure how to go about working around a bug in node…)

**Comment by krocheck** [comment]
I'd like 2.2 to be close enough.  We need to scrub all the modules that have code pending first though.

**Comment by sphlabs** [comment]
@willosof is this bug squashed with the release of 2.1.4?

**Comment by Julusian** [comment]
@sphlabs it should be. that is one of two changes in 2.1.4
